[package]
name = "bids-subset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
globwalk = "0.8.1"
lazy_static = "1.4.0"
walkdir = "2.4.0"
